version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
permissions: 
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
hooks:
  # BeforeInstall: 
  #   - location: scripts/dockerbuild.sh
  #   runas: root
  # AfterInstall: scripts/
  ApplicationStart:
    - location: scripts/dockerbuild.sh
    runas: root
    
    - location: script/dockerpush.sh
    runas: root
  # ValidateService: