name: Docker Image CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v1

      - name: Docker
      - run: |
          docker build . --file Docker file --tag teste2:teste2
          docker run -p 8080:8080 -d 