name: Docker Image CI

on: 
  push:
    branches: [main]

jobs:

# USING GIT PULL..
  test-message_build-container:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test message
        run: npm run test

      - name: Docker logout
        run: docker logout

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_LOGIN }}/${{ github.event.head_commit.message }}:${{ github.run_number }}

      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_HUB_LOGIN }}/${{ github.event.head_commit.message }}:${{ github.run_number }}

  run-container-EC2:
    needs: test-message_build-container
    runs-on: self-hosted

    steps:
      - name: Stop all docker containers
        run: docker stop $(docker ps -a -q)

      - name: Docker logout
        run: docker logout

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker pull
        run: docker pull ${{ secrets.DOCKER_HUB_LOGIN }}/${{ github.event.head_commit.message }}:${{ github.run_number }}

      - name: Docker Run
        run: docker run -d -p 8080:8080 ${{ secrets.DOCKER_HUB_LOGIN }}/${{ github.event.head_commit.message }}:${{ github.run_number }}

