name: Docker Image CI

on: 
  push:
    branches: [main]

jobs:

  build-container:
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3
      - name: Build the docker image
      - run: echo teste
