name: Docker Image CI

on: 
  push:
    branches: [main]

jobs:

# USING GIT PULL
#   build-container:
#     runs-on: self-hosted
#     steps:
#       - name: Pull git project
#         run: git pull

#       - name: Stop all docker containers
#         run: docker stop $(docker ps -a -q)

#       - name: Build docker image
#         run: docker build . --file Dockerfile --tag teste2:teste2

#       - name: Run docker image
#         run: docker run -d -p 8080:8080 teste2:teste2

  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: willians9620
          password: @W1ll14ns9620
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          # context: "{{defaultContext}}:mysubdir"
          push: true
          tags: user/app:latest
      # - name: create file
      #   run: docker image ls -a
      # - name: Pull git project
      #   run: git pull

      # - name: Stop all docker containers
      #   run: docker stop $(docker ps -a -q)

      # - name: Build docker image
      #   run: docker build . --file Dockerfile --tag teste2:teste2

      # - name: Run docker image
      #   run: docker run -d -p 8080:8080 teste2:teste2